In [2]:
import numpy as np

In [3]:
# np.array is the basic object for np
my_arr=np.array([1,2,3,4])

In [5]:
my_arr.type

AttributeError: 'numpy.ndarray' object has no attribute 'type'

In [4]:
my_arr.dtype

dtype('int64')

In [6]:
my_arr.shape   # single dimension, len=4

(4,)

In [8]:
my_arr.astype(float)

array([1., 2., 3., 4.])

In [11]:
my_arr.mean()   #np.mean(my_arr)

my_arr.std() 

my_arr.sum()

In [15]:
n=10
np.zeros(n)
np.ones(n)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [18]:
my_fives=my_arr+5
my_fives=my_arr*5
my_fives

array([ 5, 10, 15, 20])

In [19]:
np.zeros_like(my_fives)

array([0, 0, 0, 0])

In [20]:
np.exp(my_arr)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [21]:
np.arange(1,10,2)  # start and step are optional

array([1, 3, 5, 7, 9])

In [22]:
np.dot(my_arr,my_arr)

30

In [23]:
np.pi

3.141592653589793

In [24]:
import scipy.special   # some sub-module is not downloaded together with the main module

In [25]:
scipy.special.erf(my_arr)   # error function (erf): cumulative of normal distribution
# a normal distrib. centered at zero, x axis is my_arr, what is the area covered

array([0.84270079, 0.99532227, 0.99997791, 0.99999998])

In [29]:
import scipy.stats   

In [30]:
scipy.stats.pearsonr(x,y)   # can also take series in pandas

AttributeError: module 'scipy.stats' has no attribute 'pearson'

In [33]:
scipy.stats.pearsonr(my_arr,my_arr)

(1.0, 0.0)

In [32]:
my_slow_arr=[0,1,2,3]
for value in my_slow_arr:
    print(value*2)

0
2
4
6


In [34]:
def multiply_python(arr):
    new_arr=np.zeros_like(arr)
    for i, value in enumerate(arr):
        new_arr[i]=value*2
    return new_arr


In [35]:
my_arr=np.arange(1000)

In [38]:
%timeit multiply_python(my_arr)  # try 1000 times, and give time.  # magic func in jupyter

283 µs ± 1.54 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
