In [1]:
# Practice 1: Heritability
import numpy as np
import pandas as pd

import altair as alt

In [2]:
df = pd.read_csv('data/grant_heredity.csv', comment='#')
df.tail()

species  offspring beak depth (mm)  parent beak depth (mm)
538  scandens                     9.4899                  9.6516
539  scandens                     9.5962                  9.7572
540  scandens                     9.6873                  9.8854
541  scandens                     9.5203                 10.0023
542  scandens                     9.6646                  9.3914

In [3]:
# heritability is defined as the ratio of the covariance between the parental and offspring traits to the variance 
# of the parental traits.
# G. fortis and G. scandens

ft_off=df.loc[df['species']=='fortis','offspring beak depth (mm)'].values
ft_par=df.loc[df['species']=='fortis','parent beak depth (mm)'].values

sd_off=df.loc[df['species']=='scandens','offspring beak depth (mm)'].values
sd_par=df.loc[df['species']=='scandens','parent beak depth (mm)'].values

In [4]:
ft_off.shape

(413,)

In [5]:
ft_her = np.cov(ft_off,ft_par)[1,1] / np.var(ft_par)
sd_her = np.cov(sd_off,sd_par)[1,1] / np.var(sd_par)

ft_her,sd_her

(1.0024271844660186, 1.007751937984496)

In [6]:
# boostrap for fortis

In [35]:
reps = 10

ft_her_bs = np.empty(reps)

inds = np.arange(len(ft_off))

for i in range(reps):
    
    inds_bs = np.random.choice(inds,replace=True,size=len(ft_off))

    ft_off_bs = ft_off[inds_bs]
    ft_par_bs = ft_par[inds_bs]
    
    ft_her_bs[i] = np.cov(ft_off_bs,ft_par_bs)[0,1] / np.var(ft_par_bs)

In [23]:
inds

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129])

In [17]:
ft_off_bs

array([ 8.6 ,  9.94,  9.34,  9.77,  9.58,  9.37, 10.16,  9.64,  9.58,
        8.8 ,  9.4 ,  9.91,  9.52,  9.45, 10.  ,  9.3 ,  9.18,  9.81,
        9.9 ,  9.2 ,  9.85,  7.4 ,  9.59,  9.21,  8.7 ,  9.1 ,  9.67,
        8.11,  9.9 ,  9.28, 10.29,  9.5 ,  9.26,  9.06,  9.46,  9.48,
        9.69,  8.75, 10.18,  9.87,  9.32,  9.28,  9.3 ,  8.11,  9.3 ,
        9.54,  8.44, 10.3 ,  9.44,  9.95,  9.05, 10.  ,  9.5 ,  8.1 ,
        9.83, 10.02,  9.04,  8.95,  8.89, 10.46,  9.64,  9.75,  9.2 ,
       10.12,  8.8 , 10.  ,  9.4 ,  8.9 ,  9.03,  9.89,  8.94, 10.04,
       10.1 ,  9.72,  9.18, 10.39,  9.74,  9.86,  8.63,  8.9 ,  9.03,
        9.64,  9.9 , 10.58,  9.77,  7.9 ,  9.5 ,  9.43,  9.07,  7.83,
        9.  ,  7.83, 10.6 ,  8.01,  8.1 , 10.3 ,  8.9 ,  9.49,  9.3 ,
       10.18,  7.73,  9.65,  9.32,  9.96,  9.46,  8.86,  8.35,  8.49,
        8.8 , 10.12,  8.79,  9.69,  9.03,  9.43,  8.75,  9.55,  8.6 ,
        9.18,  9.51,  8.5 , 10.16,  9.54,  9.43,  9.82,  9.07,  9.09,
        9.34,  8.71,

In [18]:
x=np.arange(13)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [19]:
x[np.arange(3,13)]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [40]:
# sd
sd_her_bs = np.empty(reps)
inds = np.arange(len(sd_off))

for i in range(reps):
    
    inds_bs = np.random.choice(inds,replace=True,size=len(sd_off))
    sd_off_bs = sd_off[inds_bs]
    sd_par_bs = sd_par[inds_bs]
    
    sd_her_bs[i] = np.cov(sd_off_bs,sd_par_bs)[0,1] / np.var(sd_par_bs)

In [41]:
# confidence intervals

np.percentile(sd_her_bs,[2.5,97.5]), ft_her

(array([0.41144959, 0.65045815]), 1.0024271844660186)

In [22]:
np.percentile(sd_her_bs,[2.5,97.5]), sd_her

(array([1.00775194, 1.00775194]), 1.007751937984496)